# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 964a32adb75dd6e89aa067ef3a40d1e0e32de37914d6c6906b07e3ecb72914623af0fcbf239ac7971fe6bc46d4517899fab37ad8ff7490994efe61092d759c00

test:
  secret_key_base: 4fffd67214927ef1b098324f43418df4092752ab556e2acd2c2cc5b7ae79b4e395da709f8994eea61fd00de18836e33d2baf3655586002abbf60ad1441697df2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
